version: "3.9"

services:
  # app:
  #   container_name: go-music-app
  #   image: app
  #   env_file:
  #     - .env
  #   build:
  #     context: ..
  #     dockerfile: dockerfiles/Dockerfile
  #     args:
  #       APP_DIR: ${APP_DIR}
  #       STATIC_DIR: ${STATIC_DIR}
  #   ports:
  #     - "${APP_PORT}:${APP_PORT}"
  #   volumes:
  #     - ../uploads:${UPLOADS_DIR}
  #   depends_on:
  #     postgres:
  #       condition: service_healthy

  postgres:
    container_name: ${POSTGRES_CONTAINER_NAME}
    image: postgres:latest
    env_file: .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - database_postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 3s
      timeout: 3s
      retries: 3

  pgadmin:
    container_name: go-music-pgadmin
    image: dpage/pgadmin4
    env_file: .env
    ports:
      - ${PGADMIN_LISTEN_PORT}:${PGADMIN_LISTEN_PORT}
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  database_postgres:
